#!/bin/zsh

is_builtin() {
  : ${1?"USAGE: is_builtin <builtin-name>"}
  builtin type "${1}" | grep builtin &>/dev/null || return 1
}

is_alias() {
  : ${1?"USAGE: is_alias <alias-name>"}
  builtin type "${1}" | grep "is an alias for" &>/dev/null || return 1
}

is_function() {
  : ${1?"USAGE: is_function <function-name>"}
  builtin type "${1}" | grep function &>/dev/null || return 1
}

is_cmd() {
  : ${1?"USAGE: is_cmd <bin-name>"}
  command which "${1}" &>/dev/null || return 1
}

dispatch_sudo() {
  : ${2?"USAGE: dispatch_sudo <function_name> <command>"}
  builtin which "${1}" &>/dev/null || return 1
  is_cmd "${2}" || return 1

  eval "${(q)2}() {
  if ${(q)1} \$@; then
    command sudo ${(q)2} \$@
  else
    command ${(q)2} \$@
  fi
}"
}

eval "restore_tty() { stty `stty -g` }"
