#!/bin/zsh

function v2avi
{
	: ${1?"USAGE: v2avi <inputvideo> [outfile]"}
  local OUTFILE="${2:-${1:r}.avi}"
	mencoder "$1" -ovc xvid -xvidencopts bitrate=1000:autoaspect -vf pp=lb -oac mp3lame -lameopts fast:preset=standard -o "$OUTFILE"
}

function v2mp3
{
	: ${2?"USAGE: v2mp3 <inputvideo> [outfile]"}
  local OUTFILE="${2:-${1:r}.mp3}"
	ffmpeg -i "$1" -ab 192596 -ac 2 -ar 44100 -vn "$OUTFILE"
}

function v2mp4
{
	: ${2?"USAGE: v2mp4 inputvideo outputaudio"}
	ffmpeg -i "$1" -f mp4  -maxrate 1000 -qmin 3 -qmax 5 -bufsize 4096 -g 300 -s 320x180 -padtop 30 -padbottom 30 -ab 128 -b 400 "$2"
}
function m4a2mp3
{
  : ${1?"USAGE m4a2mp3 <file.ext> [outfile]"}
  local OUTFILE="${2:-${1:r}.mp3}"
  lame =(faad -w "$1") "$OUTFILE"
}

function v23gp
{
    : ${1?"USAGE: v23gp <infile.ext> [outfile.3gp]"}
    local OUTFILE="${2:-${1:r}.3gp}"
    ffmpeg -i "$1" -s 176x144 -vcodec h263 -r 25 -b 200 -ab 6.7k -sameq -acodec libopencore_amrnb -ac 1 -ar 8000 "$OUTFILE"
}

function all2wav
{
  : ${1?"USAGE: all2wav <file.ext> [outfile]"}
  local OUTFILE="${2:-${1:r}.wav}"
  mplayer -really-quiet "$1" -ao pcm:file="$OUTFILE" -novideo
}

function all2mp3
{
  : ${1?"USAGE: all2mp3 <file.ext> [outfile]"}
  local OUTFILE="${2:-${1:r}.mp3}"
  lame =(all2wav "$1" /dev/stdout) "$OUTFILE"
}

function droid_video
{
  : ${1?"USAGE: droid_video <input> [putfile]"}
  local OUTFILE="${2:-${1:r}.mp4}"
  ffmpeg -i "$1" -s 800x480 -vcodec mpeg4 -acodec aac -strict experimental -ac 2 -ar 16000 -r 15 -ab 32000 -aspect 16:9 -y "$OUTFILE"
}
